{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "env": {
    "CL_SOURCE_REGISTRY": "${{ github.workspace }}/"
  },
  "jobs": {
    "linter": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin/2.4.6"
      },
      "steps": [
        {
          "name": "Install libev",
          "run": "sudo apt-get install libev4",
          "shell": "bash"
        },
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "ultralisp",
            "qlot-version": "1.7.1",
            "cache": "false"
          }
        },
        {
          "name": "Change dist to Ultralisp if qlfile does not exist",
          "run": "if [[ ! -e qlfile ]]; then echo 'dist ultralisp http://dist.ultralisp.org' > qlfile; fi",
          "shell": "bash"
        },
        {
          "name": "Update Qlot",
          "run": "qlot update --no-deps",
          "shell": "bash"
        },
        {
          "name": "Install SBLint wrapper",
          "run": "qlot exec ros install 40ants-asdf-system 40ants-linter",
          "shell": "bash"
        },
        {
          "name": "Run Linter",
          "run": "qlot exec 40ants-linter --system \"ultralisp\"",
          "shell": "bash"
        }
      ]
    },
    "run-tests": {
      "services": {
        "postgres": {
          "image": "postgres:10",
          "env": {
            "POSTGRES_USER": "ultralisp",
            "POSTGRES_PASSWORD": "ultralisp"
          },
          "options": "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5",
          "ports": [
            "5432:5432"
          ]
        }
      },
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin/2.4.6"
      },
      "steps": [
        {
          "name": "Install libev",
          "run": "sudo apt-get install libev4",
          "shell": "bash"
        },
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "ultralisp",
            "cache": "true"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "ultralisp"
          }
        }
      ]
    }
  }
}
